[tool.poetry]
name = "translator"
version = "0.1.0"
description = ""
authors = ["Sashavav"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pre-commit = "^4.2.0"
pytest = "^8.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
